config/routes.rb
Rails.application.routes.draw do
  root 'people#index'

  resources :people, only: %i[index]

  get 'cards/download'
  resources :cards, only: %i[show create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :person
end

app/models/concerns/calculation_title_score.rb
module CalculationTitleScore
  # 職業の近さからスコアを計算する
  # スコアが高ければその職業の類似度が高い
  TITLE_KIND = {
    'フロントエンドエンジニア' => 0,
    'サーバーサイドエンジニア' => 0,
    'PM' => 15,
    '個人営業' => 75,
    '法人営業' => 85,
    'コンサルタント' => 100,
    '商品企画' => 30,
    '人事' => 50,
    '広報' => 40,
  }.freeze

  def calculation(title_a, title_b)
    100 - (TITLE_KIND[title_a] - TITLE_KIND[title_b]).abs
  end
end

app/models/concerns/s3_usable.rb
module S3Usable
  extend ActiveSupport::Concern

  def s3_bucket_base(bucket_name)
    bucket = s3_resource.bucket(bucket_name)
    bucket.exists? ? bucket : s3_resource.create_bucket(bucket: bucket_name)
  end

  def s3_resource
    @s3_resource ||= Aws::S3::Resource.new(
      endpoint: 'http://minio:9000',
      region: 'us-east-1',
      access_key_id: 'ak_eight',
      secret_access_key: 'sk_eight',
      force_path_style: true,
    )
  end
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :cards, dependent: :destroy
end

app/models/sample_card_image_uploader.rb
# frozen_string_literal: true

class SampleCardImageUploader
  include S3Usable

  CARD_WIDTH  = 600
  CARD_HEIGHT = 381
  BUCKET_NAME = 'cards'

  def self.upload(card)
    new(card).upload
  end

  def initialize(card)
    @card = card
  end

  def upload
    card_image_binary = card_image_bin(
      card.organization,
      card.department,
      card.name,
      card.email,
    )
    s3_bucket.object(card.id.to_s).put(body: card_image_binary)
    puts "[CREATED] #{BUCKET_NAME}/#{card.id}" # rubocop:disable Rails/Output
  end

  private

  attr_reader :card

  def card_image_bin(org, dep, name, email)
    image = Magick::Image.new(CARD_WIDTH, CARD_HEIGHT) do |options|
      color = '#' + Array.new(3) { [*126..255].sample.to_s(16) }.join
      options.background_color = color
      options.format = 'jpeg'
    end
    draw = Magick::Draw.new.tap do |d|
      d.font = 'VL-Gothic-Regular'
      d.pointsize = 40
      d.gravity = Magick::NorthWestGravity
    end
    draw.annotate(image, CARD_WIDTH, CARD_HEIGHT, 0, 0, "#{org}\n#{dep}")
    draw.pointsize = 32
    draw.gravity = Magick::SouthEastGravity
    draw.annotate(image, CARD_WIDTH, CARD_HEIGHT, 0, 0, "#{name}\n#{email}")
    image.to_blob
  end

  def s3_bucket
    s3_bucket_base(BUCKET_NAME)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    # TODO: implement me
  end

  def create
    ActiveRecord::Base.transaction do
      card = Person.create.cards.create!(card_params) # TODO:
      SampleCardImageUploader.upload(card)
    end

    head :created
  end

  def download
    # TODO: implement me
    render json: { todo: 'implement me' }
  end

  private

  def card_params
    params.permit(:name, :email, :organization, :department, :title)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = [Person.first] # TODO
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<section class="hero is-medium">
  <div class="hero-head is-eight">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item" href="/">
            Seven
          </a>
        </div>
      </div>
    </nav>
  </div>
</section>

app/views/layouts/_search_form.html.erb
<div class='search-form-wrapper'>
  <form class='search-form has-icons-left has-icons-right control'>
    <input class='input' type='text' placeholder='会社名・氏名で検索' name='query'>
    <span class='icon is-left'>
      <i class='fas fa-search'></i>
    </span>
    <button class='button'>検索</button>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Seven | 名刺管理アプリ</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.10.0/css/all.css'>
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.2.1/font-awesome-animation.css' type='text/css' media='all' />
  <link rel='stylesheet' href='https://unpkg.com/bulma@0.8.2/css/bulma.min.css' />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <%= yield %>
</body>

</html>

app/views/people/index.html.erb
<div class='container'>
  <%= render 'layouts/search_form' %>
  <div class='download-button'>
    <%= link_to 'CSVダウンロード', cards_download_path, class: 'button' %>
  </div>
  <% @people.each do |person| %>
    <div class='columns features'>
      <div class='column is-12'>
        <% person.cards.each_with_index do |card, i| %>
          <div class="card is-shady <%= i == 0 ? 'main-card' : '' %>">
            <div class='card-image'>
              <%= image_tag card_path(card.id) %>
            </div>
            <div class='card-content'>
              <div class='content'>
                <h4><%= card.name %></h4>
                <span><%= card.organization %> <%= card.department %></span>
              </div>
              <% if i == 0 && person.cards.length > 1 %>
                <div class='card-count'>
                  他に<%= person.cards.length - 1 %>件名刺があります
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class='person-spacer'></div>
  <% end %>
</div>